name: Cypress Tests

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run test-run
        env:
          CYPRESS_username: ${{ secrets.CYPRESS_USERNAME }}
          CYPRESS_password: ${{ secrets.CYPRESS_PASSWORD }}

      - name: Upload Mochawesome Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: cypress/screenshots

      - name: Upload Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: videos
          path: cypress/videos